package lotr;

import static lotr.AdventureCard.Type.EVENT;
import static lotr.AdventureCard.Type.MISSION;
import static lotr.AdventureCard.Type.POWER;

public enum AdventureCard {

    APPOINT_A_SECOND_LEADER_1(EVENT),
    APPOINT_A_SECOND_LEADER_2(EVENT),
    APPOINT_A_SECOND_LEADER_3(EVENT),
    APPOINT_A_SECOND_LEADER_4(EVENT),
    WINTER_STORMS(EVENT),
    RAIDERS(EVENT),
    MUSTERING_OF_MIDDLE_EARTH(EVENT),
    LOCAL_UPRISING(EVENT),
    CORSAIRS_OF_UMBAR(EVENT),
    THE_BLACK_GATES_OPEN(EVENT),
    THEYVE_BROUGHT_A_CAVE_TROLL(EVENT),
    THE_ENTMOOT(EVENT),
    ARAGORN_ARRIVES(EVENT),
    //
    ELVEN_HALLS(POWER),
    MOUNT_DOOM(POWER),
    EREBOR(POWER),
    HOBBITON(POWER),
    HARLOND(POWER),
    GREY_HAVENS(POWER),
    WEATHERTOP(POWER),
    MOUNT_GUNDABAD(POWER),
    CARN_DUM(POWER),
    BREE(POWER),
    LOTHLORIEN(POWER),
    RAUROS(POWER),
    DAGORLAD(POWER),
    EASTERLING_ENCAMPMENT(POWER),
    OSGILIATH(POWER),
    ERECH(POWER),
    PELARGIR(POWER),
    DOL_AMROTH(POWER),
    HARADRIM_ENCAMPMENT(POWER),
    EDORAS(POWER),
    THARBAD(POWER),
    GATES_OF_MORIA(POWER),
    //
    GRIMA_WORMTONGUE_1(MISSION),
    GRIMA_WORMTONGUE_2(MISSION),
    COURAGE_ALONE_WILL_NOT_SAVE_YOU(MISSION),
    YOU_SHALL_NOT_PASS_1(MISSION),
    YOU_SHALL_NOT_PASS_2(MISSION),
    AMBUSH(MISSION),
    THE_ENEMY_IS_AT_HAND(MISSION),
    MOVE_BY_NIGHT(MISSION),
    THE_WAY_IS_UNDER_THE_MOUNTAINS_1(MISSION),
    THE_WAY_IS_UNDER_THE_MOUNTAINS_2(MISSION),
    VIOLENT_STORMS(MISSION),
    BORNE_TO_ANOTHER_PLACE(MISSION),
    A_BALROG_IS_COME(MISSION),
    BOROMIR_TRIES_TO_SEIZE_THE_ONE_RING(MISSION),
    KNIFE_IN_THE_DARK(MISSION),
    DANGEROUS_CROSSING(MISSION),
    GOLLUM(MISSION),
    HUNT_FOR_THE_RINGBEARER(MISSION),
    SIEGE_MACHINES(MISSION),
    STRATEGIC_WITHDRAWAL(MISSION),
    BLACK_SAILS(MISSION),
    FARAMIR_FINDS_TTHE_RINGBEARER(MISSION),
    CAPTURED_BY_ORCS(MISSION),
    SHELOBS_LAIR(MISSION),
    SMEAGOL(MISSION);

    private Type type;

    private AdventureCard(Type t) {
        this.type = t;
    }

    public Type type() {
        return type;
    }

    public static enum Type {
        MISSION, EVENT, POWER;
    }

}
